name: Auto format (Black+isort)

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"

permissions:
  contents: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install black==24.8.0 isort==5.13.2
      - run: |
          isort .
          black .
      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "style: auto-format with black & isort"
            git push
          fi
