name: Auto format (Black+isort)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "**/*.py"

permissions:
  contents: write

jobs:
  fmt:
    # avoid re-running on the bot's own commit
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatters
        run: pip install black==24.8.0 isort==5.13.2

      # Let the job continue even if a file can't be parsed
      - name: Run isort
        run: isort .
        continue-on-error: true
      - name: Run black
        run: black .
        continue-on-error: true

      - name: Commit & push if changed (rebase-safe)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep .; then
            git add -A
            git commit -m "style: auto-format with black & isort"
            git pull --rebase origin "${{ github.ref_name }}"
            git push origin HEAD:"${{ github.ref_name }}"
          else
            echo "No changes to commit."
          fi
