name: Python checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # Don't fail if requirements.txt is missing or heavy
      - run: pip install -r requirements.txt || true
      - run: pip install black isort flake8
      # Make lint checks non-blocking for now
      - run: black --check . || true
      - run: isort --check-only . || true
      - run: flake8 . || true
